# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the trunk branch
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.111'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet clean
          dotnet build --no-restore
      
      - name: Server test
        run: dotnet test --no-build --verbosity normal

      - name: Client test
        run: npm test -- --no-watch --no-progress
        working-directory: ./ClientApp
          
      - name: Publish zip
        run: |
          dotnet publish Malte2.Server/Malte2.Server.csproj -c Release -r win7-x64 --self-contained
          powershell -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command 'Compress-Archive -Path Malte2.Server/bin/Release/net6.0/win7-x64/publish/* -DestinationPath Malte2.zip'

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: malte2
          # A file, directory or wildcard pattern that describes what to upload
          path: Malte2.zip
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
